hackrf_sweep: fix race condition when stopping
When stopping, the process may die right before we try to read from its stdout,
generating the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qspectrumanalyzer/backends/hackrf_sweep.py", line 146, in run
    buf = self.process.stdout.read(4)
AttributeError: 'NoneType' object has no attribute 'stdout'

Catch the error instead of crashing.